### ISSUE TITLE
Add undocumented /user/profiles endpoint

### ISSUE THREAD

**Issue by astra137** [astra137/node-mojang#12]
`https://api.mojang.com/user/profiles` didn't seem to be documented, but exists and makes it possible to get a Minecraft profile name with only a session access token. If this isn't already possible somehow, is there any reason not to add this endpoint? If not, I'll branch and request a pull.

**Comment by jamen** [comment]
Does e018168219f349c5d747d11e5dc020597cb9713f implement what you are looking for?  You do seem to mention a slightly different endpoint though, and if it returns different information then I would say definitely.
