### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by astra137** [astra137/node-mojang#16]
I was casually throwing around `cost-of-modules` when I saw that `mojang` was taking up 1.69M of space in another project of mine. It seemed disproportionately large, so I want to see about trimming that down.

Obvious first step (which I forgot to do, sorry) is to not publish non-essential source files, which could be `files` field in *package.json* or using *.npmignore*. I don't which is semantically better yet. I'll read up and make a pull request.

**Comment by dscalzi** [comment]
I agree, the tests/docs can be added to .npmignore. I've read that the npm automatically ignores files which are present in the .gitignore, however if a .npmignore is present, that file is what's used. When creating the npmignore we need to be sure to include the gitignore contents.
