### ISSUE TITLE
maintenance

### ISSUE THREAD

**Issue by jamen** [astra137/node-mojang#3]
So I don't want to maintain this project because I don't do Minecraft dev.  Let me know if you want to maintain it.

Some things to think about:

 - Package needs tests
 - Does not support skins
 - Better support for [authentication](http://wiki.vg/Protocol_Encryption#Authentication)
 - Any breaking changes? No updates in over a year

cc @seanc @blazedd @modev @rom1504 @zekesonxx

**Comment by CaptainYarb** [comment]
@jamen We'd love to take over the project on the NodeCraft github team. Thanks for all the hard work you've done on this project.

**Comment by modev** [comment]
@jamen To be honest I don't have a lot of experience with OSS projects. Anyways I would love to help with this project since I heavily rely on it in some of my own projects

**Comment by seanc** [comment]
i'd be willing to take it over.

**Comment by dscalzi** [comment]
I would be willing to contribute, but not take this over full time. I'm using this library for a minecraft launcher built in Node.js so I'd like to keep this up to date and working.

**Comment by dscalzi** [comment]
@jamen I'm going to gradually be adding more API wrappers to this project. What is the procedure for deploying an update to npm?

**Comment by modev** [comment]
I would implement some test scenarios with mocha and chai. But I'm not exactly sure how to handle test credentials, since testing authentification endpoints would require a set of correct ones.
Is there anybody with some experience with Travis CI or some other CI system?

**Comment by dscalzi** [comment]
I have experience with jenkins, although I have only used it for java builds with maven.

**Comment by modev** [comment]
I think I am going to use Travis. Works great with node and is easy to set-up and free for open-source projects. I just started writing some basic tests for this project which do not require authentification. Will create a PR soon

**Comment by dscalzi** [comment]
I am working on adding skin support

**Comment by dscalzi** [comment]
I'm having an issue though. I've implemented the request exactly as it's supposed to be however the response I keep getting is

      { error: 'Forbidden', errorMessage: 'Current IP not secured' }

**Comment by modev** [comment]
@dscalzi Are you requesting the API via https:// or http://?

**Comment by jamen** [comment]
You can setup fake requests with [nock](https://github.com/node-nock) for things like credentials, which will work fine on Travis.

**Comment by modev** [comment]
I'm more worried about the correct credentials, since they are required for _auth_, _validate_, _profile_ and _invalidate_. Any idea how they can be kept private?

**Comment by jamen** [comment]
You can't if you're publishing them inside this repo as tests.  I wouldn't test the validity of Mojang's servers, as I would hope the authentication always works on their side.   (That would raise some security concerns otherwise)

I would setup mocks with `nock` that give successful and a failed authentication responses, and test the behavior this module gives when it makes the requests to them.

**Comment by dscalzi** [comment]
I'm using https.

**Comment by jamen** [comment]
I think I've added enough collaborators.  Please let me know your npm usernames if you want access to the package on npm.  Closing now, you may carry on discussion in more targeted threads.

**Comment by jamen** [comment]
And if anyone else I mentioned wants to collaborate (or otherwise), its never too late! Just let me know.
