### ISSUE TITLE
Optimizations

### ISSUE THREAD

**Issue by jamen** [astra137/node-mojang#9]
I notice in my old code there is some optimizations that I didn't make, which I would do now-a-days:

 1. Stop using array built-ins (`Array#forEach`, `map`, `reduce`, etc.)
 2. ~~Stop using `for (foo in bar)` loops on objects, opposed to `Object.keys` + regular `for`~~
 3. Caching some of the request options [that never change between each call](https://github.com/jamen/node-mojang/blob/master/lib/signout.js#L15-L17)
 4. Probably others.  Like caching requests, early exits, etc.

As always, your guys' choice.  If you want clean maintainable code, or optimized code.

**Comment by modev** [comment]
Maybe it would be more efficient if there would be a 2.x version as a complete rewrite. So it's easier to implement optimizations, features like #8 and  #7 and so on. Since everything is designed around promises it doesn't even require a lot of breaking API changes.

**Comment by astra137** [comment]
May I ask why a developer might avoid using array built-ins?

**Comment by jamen** [comment]
I meant inside our code, for e.g. [here](https://github.com/jamen/node-mojang/blob/master/lib/profile.js#L15).  But, I can leave a lot of this stuff up to the person who decides to write it.  Closing
